export const MILESTONE_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "id",
    "title",
    "kind",
    "objective",
    "rationale",
    "dependencies",
    "permittedPaths",
    "exclusions",
    "acceptanceCriteria",
    "requiredTests",
    "verificationCommands",
    "expectedArtifacts",
    "terminalConditions",
    "estimatedFileCount",
    "requiresBrowserInspection",
    "requiresHeadlessEvaluation",
    "hiddenValidation",
    "verticalSlice",
  ],
  properties: {
    schemaVersion: { type: "string", enum: ["1.1.0"] },
    id: { type: "string", pattern: "^[a-z][a-z0-9-]{2,63}$" },
    title: { type: "string", minLength: 3, maxLength: 120 },
    kind: {
      type: "string",
      enum: [
        "tooling",
        "verification",
        "lifecycle",
        "feature",
        "documentation",
      ],
    },
    objective: { type: "string", minLength: 10 },
    rationale: { type: "string", minLength: 10 },
    dependencies: { type: "array", items: { type: "string" } },
    permittedPaths: { type: "array", minItems: 1, items: { type: "string" } },
    exclusions: { type: "array", minItems: 2, items: { type: "string" } },
    acceptanceCriteria: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "description", "evidence"],
        properties: {
          id: { type: "string" },
          description: { type: "string" },
          evidence: { type: "string" },
        },
      },
    },
    requiredTests: { type: "array", minItems: 1, items: { type: "string" } },
    verificationCommands: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "executable", "args", "parser", "timeoutMs"],
        properties: {
          id: { type: "string" },
          executable: { type: "string", enum: ["pnpm", "node", "git"] },
          args: { type: "array", items: { type: "string" } },
          parser: { type: "string", enum: ["exit-code", "pnpm-verify"] },
          timeoutMs: {
            anyOf: [{ type: "integer", minimum: 1000 }, { type: "null" }],
          },
        },
      },
    },
    expectedArtifacts: {
      type: "array",
      minItems: 1,
      items: { type: "string" },
    },
    terminalConditions: {
      type: "array",
      minItems: 1,
      items: { type: "string" },
    },
    estimatedFileCount: { type: "integer", minimum: 1 },
    requiresBrowserInspection: { type: "boolean" },
    requiresHeadlessEvaluation: { type: "boolean" },
    hiddenValidation: {
      type: "object",
      additionalProperties: false,
      required: ["requested", "checkpointId"],
      properties: {
        requested: { type: "boolean" },
        checkpointId: {
          anyOf: [{ type: "string" }, { type: "null" }],
        },
      },
    },
    verticalSlice: {
      type: "object",
      additionalProperties: false,
      required: [
        "mode",
        "userGoal",
        "publicActionKinds",
        "sharedRuleOwners",
        "standardCompositionOwner",
        "persistenceReplayEvidence",
        "nodeWorkerParityEvidence",
        "inspectableConsequence",
        "exception",
      ],
      properties: {
        mode: {
          type: "string",
          enum: ["not-applicable", "integrated", "exception"],
        },
        userGoal: {
          anyOf: [{ type: "string" }, { type: "null" }],
        },
        publicActionKinds: { type: "array", items: { type: "string" } },
        sharedRuleOwners: { type: "array", items: { type: "string" } },
        standardCompositionOwner: {
          anyOf: [{ type: "string" }, { type: "null" }],
        },
        persistenceReplayEvidence: {
          type: "array",
          items: { type: "string" },
        },
        nodeWorkerParityEvidence: {
          type: "array",
          items: { type: "string" },
        },
        inspectableConsequence: {
          anyOf: [
            {
              type: "object",
              additionalProperties: false,
              required: [
                "readModelPaths",
                "browserEvidenceRequired",
                "description",
              ],
              properties: {
                readModelPaths: {
                  type: "array",
                  items: { type: "string" },
                },
                browserEvidenceRequired: { type: "boolean" },
                description: { type: "string" },
              },
            },
            { type: "null" },
          ],
        },
        exception: {
          anyOf: [
            {
              type: "object",
              additionalProperties: false,
              required: [
                "kind",
                "justification",
                "immediateConsumerMilestoneId",
                "consumerContract",
              ],
              properties: {
                kind: {
                  type: "string",
                  enum: [
                    "kernel-only",
                    "fixture-only",
                    "migration-only",
                    "preview-only",
                  ],
                },
                justification: { type: "string" },
                immediateConsumerMilestoneId: { type: "string" },
                consumerContract: { type: "string" },
              },
            },
            { type: "null" },
          ],
        },
      },
    },
  },
} as const;

export const REVIEW_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "decision", "summary", "findings", "checks"],
  properties: {
    schemaVersion: { type: "string", enum: ["1.0.0"] },
    decision: { type: "string", enum: ["approve", "reject", "escalate"] },
    summary: { type: "string" },
    findings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["code", "severity", "message", "evidence"],
        properties: {
          code: { type: "string" },
          severity: {
            type: "string",
            enum: ["low", "medium", "high", "critical"],
          },
          message: { type: "string" },
          evidence: { type: "string" },
        },
      },
    },
    checks: {
      type: "object",
      additionalProperties: false,
      required: [
        "acceptanceEvidence",
        "architectureCompliance",
        "testQuality",
        "noSuspiciousShortcuts",
        "noScopeReduction",
        "regressionsHandled",
      ],
      properties: {
        acceptanceEvidence: { type: "boolean" },
        architectureCompliance: { type: "boolean" },
        testQuality: { type: "boolean" },
        noSuspiciousShortcuts: { type: "boolean" },
        noScopeReduction: { type: "boolean" },
        regressionsHandled: { type: "boolean" },
      },
    },
  },
} as const;

export const RECONCILIATION_REVIEW_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "reconciliationId",
    "sourceVerifiedCommit",
    "candidateCommit",
    "candidateTree",
    "commitRangeManifestSha256",
    "decision",
    "summary",
    "findings",
    "checks",
  ],
  properties: {
    schemaVersion: { type: "string", enum: ["1.0.0"] },
    reconciliationId: { type: "string" },
    sourceVerifiedCommit: { type: "string", pattern: "^[a-f0-9]{40}$" },
    candidateCommit: { type: "string", pattern: "^[a-f0-9]{40}$" },
    candidateTree: { type: "string", pattern: "^[a-f0-9]{40}$" },
    commitRangeManifestSha256: {
      type: "string",
      pattern: "^[a-f0-9]{64}$",
    },
    decision: { type: "string", enum: ["approve", "reject", "escalate"] },
    summary: { type: "string", minLength: 1 },
    findings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["severity", "code", "message", "path"],
        properties: {
          severity: {
            type: "string",
            enum: ["low", "medium", "high", "critical"],
          },
          code: { type: "string" },
          message: { type: "string" },
          path: { anyOf: [{ type: "string" }, { type: "null" }] },
        },
      },
    },
    checks: {
      type: "object",
      additionalProperties: false,
      required: [
        "completeCommitLineage",
        "protectedIntegrity",
        "noFabricatedHistory",
        "d031ScopeCompliance",
        "d031MigrationIntegrity",
        "d031NodeWorkerParity",
        "commandOwnedEvidenceValidity",
        "verificationTierNonAuthority",
        "invariantSuiteQuality",
        "selectorShadowOnlyEnforcement",
        "telemetryNonSemanticBehavior",
        "artifactContainmentAndNonDeletion",
        "stateMigrationAndRecovery",
        "verticalMilestonePolicy",
        "dependencyValidNextProposal",
        "noScopeReductionOrSuspiciousShortcut",
      ],
      properties: {
        completeCommitLineage: { type: "boolean" },
        protectedIntegrity: { type: "boolean" },
        noFabricatedHistory: { type: "boolean" },
        d031ScopeCompliance: { type: "boolean" },
        d031MigrationIntegrity: { type: "boolean" },
        d031NodeWorkerParity: { type: "boolean" },
        commandOwnedEvidenceValidity: { type: "boolean" },
        verificationTierNonAuthority: { type: "boolean" },
        invariantSuiteQuality: { type: "boolean" },
        selectorShadowOnlyEnforcement: { type: "boolean" },
        telemetryNonSemanticBehavior: { type: "boolean" },
        artifactContainmentAndNonDeletion: { type: "boolean" },
        stateMigrationAndRecovery: { type: "boolean" },
        verticalMilestonePolicy: { type: "boolean" },
        dependencyValidNextProposal: { type: "boolean" },
        noScopeReductionOrSuspiciousShortcut: { type: "boolean" },
      },
    },
  },
} as const;
